{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "latin-square.fullname" . }}
  labels:
    {{- include "latin-square.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "latin-square.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
{{- end }}